server:
  port: 9080

spring:
  security:
    filter:
      dispatcher-types: async, error, request, forward
    saml2:
      relyingparty:
        registration:
          okta-saml:
            assertingparty:
              verification:
                credentials:
                  - certificate-location: classpath:credentials/okta.cert
              metadata-uri: https://dev-14793550.okta.com/app/exke4qnphubxOqwh25d7/sso/saml/metadata
            singlelogout:
              binding: POST
              url: "{baseUrl}/logout/saml2/slo"
              responseUrl: "{baseUrl}/logout/saml2/slo"
#            acs:
#                location: "{baseUrl}/login/saml2/sso/okta-saml"
#                binding: POST
#            signing:
#              credentials:
#                - certificate-location: classpath:credentials/rp-certificate.crt
#                  private-key-location: classpath:credentials/rp-private.key
